# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: xgboostMasssLinear_quantEGAI
phenotype: bodymass
model: xgboost
procedure: one-step

  #### HYPERPARAMETERS ####
  # TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: xgboost_space

  # FIXED HYPERPARAMETERS
fixed:
  objective: reg:quantileerror
  quantile_alpha: [0.05, 0.5, 0.95]

    #### Settings for hyperparameter optimization ####
    # Number of iterations for hyperparameter optimizationhyp_settings
hyp_settings:
  max_evals: 30

### Train and test between populations? ###
# If yes, the model will be trained on one population and tested on another
train_across: yes
# If yes, the model will be trained on all island except one and tested on the remaining island
train_across_islands: yes

