# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: linearlgbmMass_70kEGAIFI
phenotype: bodymass
model: lightgbm
procedure: two-step
data: _70k
  #### HYPERPARAMETERS ####
  # TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: lgbm_space

  # FIXED HYPERPARAMETERS
fixed:
  # fit_intercept: True
  # booster: gblinear
  # objective: regression
  force_col_wise: true
  # data_sample_strategy: goss
  # nthread: 4
  # early_stopping_rounds: 25
  # n_estimators: 50
  # objective: reg:absoluteerror
  # huber_slope: 0.1 # 1 is default value
  # objective: reg:quantileerror
  # quantile_alpha: [0.05, 0.5, 0.95]

    #### Settings for hyperparameter optimization ####
    # Number of iterations for hyperparameter optimizationhyp_settings
hyp_settings:
  max_evals: 30

### Train and test between populations? ###
# If yes, the model will be trained on one population and tested on another
train_across: no
# If yes, the model will be trained on all island except one and tested on the remaining island
train_across_islands: yes
