# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: xgboostTarsusEGA
phenotype: tarsus
model: xgboost
procedure: one-step

#### HYPERPARAMETERS ####
# TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: xgboost_space

# FIXED HYPERPARAMETERS
fixed:
  booster: gbtree

#### Settings for hyperparameter optimization ####
# Number of iterations for hyperparameter optimization
hyp_settings:
  max_evals: 30

### Train and test between populations? ###
train_across: yes
