# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: xgboostMasssLinearEGA
phenotype: bodymass
model: xgboost
procedure: one-step

#### HYPERPARAMETERS ####
# TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: xgboost_linear_space

# FIXED HYPERPARAMETERS
fixed:
  booster: gblinear

#### Settings for hyperparameter optimization ####
# Number of iterations for hyperparameter optimization
hyp_settings:
  max_evals: 30

### Train and test between populations? ###
train_across: yes
