# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: xgboostMasssDartEGA
phenotype: bodymass
model: xgboost
procedure: one-step

#### HYPERPARAMETERS ####
# TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: xgboost_space

# FIXED HYPERPARAMETERS
fixed:
  booster: dart
  rate_drop: 0.2
  one_drop: 1

#### Settings for hyperparameter optimization ####
# Number of iterations for hyperparameter optimization
hyp_settings:
  max_evals: 30

### Train and test between populations? ###
train_across: yes
