# Path: config.yaml

#### DESCRIPTION ####
# Two-step xgboost model with bodymass as phenotype
#### META VARIABLES ####
name: xgboostMasssLinear_quantEGA
phenotype: bodymass
model: xgboost
procedure: one-step

  #### HYPERPARAMETERS ####
  # TUNEABLE HYPERPARAMETERS, DEFINED BY SEARCHSPACE
searchspace: xgboost_linear_space

  # FIXED HYPERPARAMETERS
fixed:
  booster: gblinear
  objective: reg:quantileerror
  quatile_alpha: [0.05, 0.5, 0.95]

    #### Settings for hyperparameter optimization ####
    # Number of iterations for hyperparameter optimizationhyp_settings
hyp_settings:
  max_evals: 30

      ### Train and test between populations? ###
train_across: yes
